<?php
namespace App\Services\Commerce;
use App\Models\{Order,OrderAllocation,OrderItem,Payment,PayoutAccount,TicketType};
use App\Support\Money;
use Illuminate\Support\Facades\{Cache,DB};
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use Throwable;
class CheckoutService {
 public function __construct(private readonly InventoryService $inventory,private readonly PaystackService $paystack,private readonly PaymentFinalizer $finalizer){}
 public function quote(array $items):array{$items=$this->normalizedItems($items);$ids=array_column($items,'ticket_type_id');$types=TicketType::with('event')->whereIn('id',$ids)->get()->keyBy('id');return $this->buildQuote($items,$types,$this->inventory->reservedQuantities($ids));}
 public function initialize(array $payload,?int $userId):array{$token=(string)$payload['checkout_token'];$hash=hash('sha256',$token);$customer=$this->normalizedCustomer($payload['customer']);$items=$this->normalizedItems($payload['items']);$fp=hash('sha256',json_encode(['customer'=>$customer,'items'=>$items],JSON_THROW_ON_ERROR));return Cache::lock("checkout:init:{$hash}",20)->block(6,function()use($hash,$fp,$customer,$items,$userId){$existing=Order::where('checkout_token_hash',$hash)->first();if($existing){if(!hash_equals($existing->cart_fingerprint,$fp))throw ValidationException::withMessages(['checkout_token'=>['This checkout token belongs to a different cart or customer.']]);return $this->continueExistingOrder($existing);}[$order,$payment]=DB::transaction(function()use($hash,$fp,$customer,$items,$userId){$ids=collect($items)->pluck('ticket_type_id')->sort()->values()->all();$types=TicketType::with('event')->whereIn('id',$ids)->orderBy('id')->lockForUpdate()->get()->keyBy('id');$quote=$this->buildQuote($items,$types,$this->inventory->reservedQuantities($ids));$order=Order::create(['public_id'=>(string)Str::ulid(),'checkout_token_hash'=>$hash,'cart_fingerprint'=>$fp,'user_id'=>$userId,'customer_first_name'=>$customer['first_name'],'customer_last_name'=>$customer['last_name'],'customer_email'=>$customer['email'],'customer_phone'=>$customer['phone'],'currency'=>$quote['currency'],'subtotal_minor'=>$quote['subtotal_minor'],'discount_minor'=>0,'total_minor'=>$quote['total_minor'],'status'=>Order::STATUS_PENDING_PAYMENT,'expires_at'=>now()->addMinutes(max(5,(int)config('commerce.reservation_minutes',20)))]);foreach($quote['items'] as $line)OrderItem::create(['order_id'=>$order->id,...$line,'currency'=>$quote['currency']]);$this->createAllocations($order,$quote['currency']);$payment=$this->createPayment($order);return[$order,$payment];},3);return $this->initializePayment($order,$payment);});}
 public function verify(string $reference,?int $userId,?string $checkoutToken):Order{$payment=Payment::with('order')->where('reference',$reference)->firstOrFail();$this->authorizeOrderAccess($payment->order,$userId,$checkoutToken);return $this->finalizer->finalizePaystack($reference,$this->paystack->verify($reference));}
 public function authorizeOrderAccess(Order $order,?int $userId,?string $checkoutToken):void{if($userId!==null&&$order->user_id!==null&&(int)$order->user_id===$userId)return;if(is_string($checkoutToken)&&$checkoutToken!==''&&hash_equals($order->checkout_token_hash,hash('sha256',$checkoutToken)))return;abort(403,'You do not have access to this order.');}
 public function publicOrderPayload(Order $order):array{$order->loadMissing('items.tickets');return['public_id'=>$order->public_id,'status'=>$order->status,'currency'=>$order->currency,'subtotal_minor'=>(int)$order->subtotal_minor,'discount_minor'=>(int)$order->discount_minor,'total_minor'=>(int)$order->total_minor,'expires_at'=>$order->expires_at?->toIso8601String(),'paid_at'=>$order->paid_at?->toIso8601String(),'items'=>$order->items->map(fn(OrderItem $i)=>['id'=>$i->id,'event_id'=>$i->event_id,'event_title'=>$i->event_title,'ticket_type_id'=>$i->ticket_type_id,'ticket_name'=>$i->ticket_name,'unit_type'=>$i->unit_type,'people_per_unit'=>(int)$i->people_per_unit,'unit_price_minor'=>(int)$i->unit_price_minor,'quantity'=>(int)$i->quantity,'line_total_minor'=>(int)$i->line_total_minor,'tickets'=>$order->isPaid()?$i->tickets->map(fn($t)=>['public_id'=>$t->public_id,'token'=>$t->token,'admit_count'=>(int)$t->admit_count,'status'=>$t->status])->values()->all():[]])->values()->all()];}
 public function payload(Order $o,?Payment $p):array{return['order'=>$this->publicOrderPayload($o),'payment'=>$p?['reference'=>$p->reference,'status'=>$p->status,'access_code'=>$p->access_code,'authorization_url'=>$p->authorization_url]:null];}
 private function continueExistingOrder(Order $o):array{$o->refresh();if(in_array($o->status,[Order::STATUS_PAID,Order::STATUS_PAYMENT_REVIEW,Order::STATUS_CANCELLED,Order::STATUS_REFUNDED],true))return $this->payload($o,$o->payments()->latest('id')->first());if($o->expires_at&&$o->expires_at->isPast()){$o->update(['status'=>Order::STATUS_EXPIRED]);throw ValidationException::withMessages(['checkout_token'=>['This checkout reservation has expired. Start a new checkout attempt.']]);}$p=$o->payments()->latest('id')->first();if($o->status===Order::STATUS_PAYMENT_FAILED)$o->update(['status'=>Order::STATUS_PENDING_PAYMENT]);if($p&&$p->status===Payment::STATUS_INITIALIZED&&$p->access_code)return $this->payload($o,$p);if(!$p||in_array($p->status,[Payment::STATUS_FAILED,Payment::STATUS_REVIEW],true))$p=$this->createPayment($o);return $this->initializePayment($o,$p);}
 private function initializePayment(Order $o,Payment $p):array{try{$x=$this->paystack->initialize($o->loadMissing('allocations'),$p);$p->update(['status'=>Payment::STATUS_INITIALIZED,'access_code'=>$x['access_code'],'authorization_url'=>$x['authorization_url']]);$o->allocations()->update(['settlement_mode'=>$x['split_used']?'paystack_split':'platform_held']);return $this->payload($o->fresh(),$p->fresh());}catch(Throwable $e){$p->update(['status'=>Payment::STATUS_FAILED,'gateway_response'=>Str::limit($e->getMessage(),255,'')]);$o->update(['status'=>Order::STATUS_PAYMENT_FAILED]);throw $e;}}
 private function createPayment(Order $o):Payment{return Payment::create(['order_id'=>$o->id,'provider'=>'paystack','reference'=>'KT-'.Str::ulid(),'amount_minor'=>(int)$o->total_minor,'currency'=>$o->currency,'status'=>Payment::STATUS_CREATED]);}
 private function createAllocations(Order $o,string $currency):void{$feeBps=max(0,min(10000,(int)config('commerce.platform_fee_bps',0)));foreach($o->items()->select('seller_user_id',DB::raw('SUM(line_total_minor) AS gross_minor'))->groupBy('seller_user_id')->get() as $g){$gross=(int)$g->gross_minor;$fee=intdiv($gross*$feeBps,10000);$pay=$g->seller_user_id?PayoutAccount::where('user_id',$g->seller_user_id)->where('status','active')->first():null;OrderAllocation::create(['order_id'=>$o->id,'seller_user_id'=>$g->seller_user_id,'payout_account_id'=>$pay?->id,'provider_subaccount_code'=>$pay?->provider_subaccount_code,'gross_minor'=>$gross,'platform_fee_minor'=>$fee,'seller_net_minor'=>max(0,$gross-$fee),'currency'=>$currency,'settlement_mode'=>'platform_held','settlement_status'=>'pending']);}}
 private function buildQuote(array $items,$types,array $reserved):array{$lines=[];$subtotal=0;$errors=[];foreach($items as $index=>$r){$id=(int)$r['ticket_type_id'];$q=(int)$r['quantity'];$t=$types->get($id);if(!$t||!$t->event||$t->event->status!=='active'||$t->event->ticket_mode!=='paid'||!$t->visible||$t->event->created_by===null){$errors["items.{$index}"]=['This ticket type is not currently available.'];continue;}if(($t->sales_start_date&&$t->sales_start_date->isFuture())||($t->sales_end_date&&$t->sales_end_date->isPast())){$errors["items.{$index}"]=['Ticket sales are not currently available.'];continue;}$a=$this->inventory->availableQuantity((int)$t->quantity,(int)($reserved[$t->id]??0));if($q>$a||($t->max_per_person&&$q>(int)$t->max_per_person)){$errors["items.{$index}"]=['Ticket quantity is unavailable.'];continue;}$price=Money::decimalToMinor($t->price);if($price<=0){$errors["items.{$index}"]=['Free tickets are not handled by paid checkout.'];continue;}$total=$price*$q;$lines[]=['ticket_type_id'=>$t->id,'event_id'=>$t->event_id,'seller_user_id'=>$t->event->created_by,'event_title'=>$t->event->title,'ticket_name'=>$t->name,'unit_type'=>$t->unit_type?:'individual','people_per_unit'=>max(1,(int)$t->people_per_unit),'unit_price_minor'=>$price,'quantity'=>$q,'line_total_minor'=>$total];$subtotal+=$total;}if($errors)throw ValidationException::withMessages($errors);return['currency'=>strtoupper((string)config('commerce.currency','NGN')),'subtotal_minor'=>$subtotal,'discount_minor'=>0,'total_minor'=>$subtotal,'items'=>$lines];}
 private function normalizedCustomer(array $c):array{return['first_name'=>trim((string)$c['first_name']),'last_name'=>trim((string)$c['last_name']),'email'=>mb_strtolower(trim((string)$c['email'])),'phone'=>trim((string)$c['phone'])];}
 private function normalizedItems(array $items):array{return collect($items)->map(fn(array $i)=>['ticket_type_id'=>(int)$i['ticket_type_id'],'quantity'=>(int)$i['quantity']])->sortBy('ticket_type_id')->values()->all();}
}