<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use App\Models\User;use Illuminate\Http\Request;use Illuminate\Support\Facades\Auth;use Illuminate\Support\Facades\Hash;use Illuminate\Support\Str;use Illuminate\Validation\ValidationException;use Laravel\Socialite\Facades\Socialite;
class AuthController extends Controller{
public function login(Request $request){$request->validate(['email'=>'required|email','password'=>'required']);if(Auth::attempt($request->only('email','password'))){$request->session()->regenerate();return response()->json(['user'=>Auth::user(),'message'=>'Login successful']);}throw ValidationException::withMessages(['email'=>['Wrong email or password']]);}
public function register(Request $request){$request->validate(['name'=>'required|string|max:255','email'=>'required|string|email|max:255|unique:users','password'=>'required|string|min:8|confirmed']);$user=User::create(['name'=>$request->name,'email'=>$request->email,'password'=>Hash::make($request->password)]);Auth::login($user);$request->session()->regenerate();return response()->json(['user'=>$user,'message'=>'Registration successful'],201);}
public function logout(Request $request){Auth::guard('web')->logout();Auth::guard('sanctum')->forgetUser();if($request->hasSession()){$request->session()->invalidate();$request->session()->regenerateToken();}return response()->json(['message'=>'Logged out successfully']);}
public function user(Request $request){return response()->json($request->user());}
public function redirectToGoogle(Request $request){try{if(!$request->session()->has('_token')){$request->session()->put('_token',csrf_token());$request->session()->save();}$socialite=Socialite::driver('google')->stateless();if(config('app.env')==='local')$socialite->setHttpClient(new \GuzzleHttp\Client(['verify'=>false]));return $socialite->redirect();}catch(\Exception $e){return redirect(rtrim((string)config('app.frontend_url'),'/').'/login?'.http_build_query(['error'=>'google_auth_failed','message'=>$e->getMessage()]));}}
public function handleGoogleCallback(Request $request){try{$socialite=Socialite::driver('google')->stateless();if(config('app.env')==='local')$socialite->setHttpClient(new \GuzzleHttp\Client(['verify'=>false]));$googleUser=$socialite->user();$user=User::updateOrCreate(['email'=>$googleUser->email],['name'=>$googleUser->name??'Google User','google_id'=>$googleUser->id,'avatar'=>$googleUser->avatar,'password'=>Hash::make(Str::random(24)),'email_verified_at'=>now()]);Auth::login($user);$request->session()->regenerate();$data=urlencode(json_encode(['id'=>$user->id,'name'=>$user->name,'email'=>$user->email,'role'=>$user->role,'avatar'=>$user->avatar],JSON_THROW_ON_ERROR));return redirect(rtrim((string)config('app.frontend_url'),'/').'/auth/google/success?user='.$data);}catch(\Exception $e){return redirect(rtrim((string)config('app.frontend_url'),'/').'/login?'.http_build_query(['error'=>'google_auth_failed','message'=>$e->getMessage()]));}}
}