<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('payout_accounts',function(Blueprint $t){$t->id();$t->foreignId('user_id')->unique()->constrained('users')->cascadeOnDelete();$t->string('provider',32)->default('paystack');$t->string('provider_subaccount_code',100)->nullable()->unique();$t->string('status',24)->default('pending');$t->string('account_name',150)->nullable();$t->string('bank_name',120)->nullable();$t->string('account_last4',4)->nullable();$t->timestamps();$t->index(['provider','status'],'idx_payout_provider_status');});
Schema::create('orders',function(Blueprint $t){$t->id();$t->char('public_id',26)->unique();$t->char('checkout_token_hash',64)->unique();$t->char('cart_fingerprint',64);$t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete();$t->string('customer_first_name',100);$t->string('customer_last_name',100);$t->string('customer_email',255);$t->string('customer_phone',50);$t->char('currency',3)->default('NGN');$t->unsignedBigInteger('subtotal_minor');$t->unsignedBigInteger('discount_minor')->default(0);$t->unsignedBigInteger('total_minor');$t->string('status',32)->default('pending_payment');$t->timestamp('expires_at')->nullable();$t->timestamp('paid_at')->nullable();$t->timestamps();$t->index(['status','expires_at'],'idx_orders_status_expiry');$t->index(['user_id','created_at'],'idx_orders_user_created');$t->index(['customer_email','created_at'],'idx_orders_email_created');});
Schema::create('order_items',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained('orders')->cascadeOnDelete();$t->foreignId('event_id')->constrained('events')->restrictOnDelete();$t->foreignId('ticket_type_id')->constrained('ticket_types')->restrictOnDelete();$t->foreignId('seller_user_id')->nullable()->constrained('users')->nullOnDelete();$t->string('event_title',150);$t->string('ticket_name',100);$t->string('unit_type',20)->default('individual');$t->unsignedInteger('people_per_unit')->default(1);$t->unsignedBigInteger('unit_price_minor');$t->unsignedInteger('quantity');$t->unsignedBigInteger('line_total_minor');$t->char('currency',3)->default('NGN');$t->timestamps();$t->unique(['order_id','ticket_type_id'],'uq_order_ticket_type');$t->index(['event_id','created_at'],'idx_order_items_event_created');$t->index(['ticket_type_id','created_at'],'idx_order_items_ticket_created');$t->index(['seller_user_id','created_at'],'idx_order_items_seller_created');});
Schema::create('order_allocations',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained('orders')->cascadeOnDelete();$t->foreignId('seller_user_id')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('payout_account_id')->nullable()->constrained('payout_accounts')->nullOnDelete();$t->string('provider_subaccount_code',100)->nullable();$t->unsignedBigInteger('gross_minor');$t->unsignedBigInteger('platform_fee_minor')->default(0);$t->unsignedBigInteger('seller_net_minor');$t->char('currency',3)->default('NGN');$t->string('settlement_mode',24)->default('platform_held');$t->string('settlement_status',24)->default('pending');$t->timestamps();$t->unique(['order_id','seller_user_id'],'uq_order_seller_allocation');$t->index(['seller_user_id','settlement_status'],'idx_allocations_seller_status');});
Schema::create('payments',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained('orders')->cascadeOnDelete();$t->string('provider',32)->default('paystack');$t->string('reference',100)->unique();$t->string('provider_transaction_id',40)->nullable()->unique();$t->unsignedBigInteger('amount_minor');$t->char('currency',3)->default('NGN');$t->string('status',24)->default('created');$t->string('access_code',150)->nullable();$t->text('authorization_url')->nullable();$t->string('channel',50)->nullable();$t->string('gateway_response',255)->nullable();$t->timestamp('paid_at')->nullable();$t->timestamp('verified_at')->nullable();$t->timestamps();$t->index(['order_id','status'],'idx_payments_order_status');});
Schema::create('tickets',function(Blueprint $t){$t->id();$t->char('public_id',26)->unique();$t->foreignId('order_item_id')->constrained('order_items')->cascadeOnDelete();$t->foreignId('event_id')->constrained('events')->restrictOnDelete();$t->foreignId('ticket_type_id')->constrained('ticket_types')->restrictOnDelete();$t->text('token');$t->char('token_hash',64)->unique();$t->unsignedInteger('admit_count')->default(1);$t->string('status',24)->default('valid');$t->timestamp('issued_at')->useCurrent();$t->timestamps();$t->index(['event_id','status'],'idx_tickets_event_status');$t->index(['order_item_id','status'],'idx_tickets_item_status');});
Schema::table('ticket_types',fn(Blueprint $t)=>$t->index(['event_id','visible'],'idx_ticket_types_event_visible')); }
public function down(): void {Schema::table('ticket_types',fn(Blueprint $t)=>$t->dropIndex('idx_ticket_types_event_visible'));foreach(['tickets','payments','order_allocations','order_items','orders','payout_accounts'] as $x)Schema::dropIfExists($x);} };